title: <p align="center"> Shades Of Cake </p>
logo: /assets/img/cakelogo.png

description:
  <p align="center">
  <a href="https://Instagram/_shades_of_cackes
 
  <br>   
READY | GET SET | BAKE !
   SHADES OF CAKE
   ASHLESHA NINAWE
   NAGPUR MH31
   9373078433
  <br>
  </p>

theme: jekyll-theme-minimal

