title: Shades Of Cake
logo: /assets/img/cakelogo.png
description:   <p align="center">
  <a href= "https://instagram.com/_shades_of_cakes__?igshid=YmMyMTA2M2Y="> Instgram</a> |
  <a href="https://github.com/Shadesofcakes">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
